### ISSUE TITLE
Could you briefly introduce your tracking network?

### ISSUE THREAD

**Issue by rochou** [adipandas/multi-object-tracker#1]
Could you briefly introduce your tracking network? thank you very much.

**Comment by adipandas** [comment]
@rochou , The object tracking algorithm is a python class.

I have included some more details and description in my code as well.

Tracker class uses the bounding boxes from the object detection model. In this case, I am using pre-trained face detection caffe model as per OpenCV compatibility.

Soon I will try to add the use case of different network models.

Hope this resolves your issue. I am closing it.
