### ISSUE TITLE
Speed is very slow

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [adipandas/multi-object-tracker#10]
Hi sir, 
         I am using the tracking_yolo_model in GTX1080Ti. But the interface speed is very very slow. Is it running in the CPU mode? 
It's roundabout 2 FPS.

**Comment by adipandas** [comment]
Yes. My example runs the network on CPU.
To work with YOLO on GPU, you may want to refer [this link](https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/).

**Comment by MuhammadAsadJaved** [comment]
OK. Thanks

**Comment by adipandas** [comment]
I have updated the codes with GPU support for the networks. You may find it useful.

**Comment by MuhammadAsadJaved** [comment]
> I have updated the codes with GPU support for the networks. You may find it useful.

That's great. Thank you.
