### ISSUE TITLE
tracking ids are changing over the time for same object

### ISSUE THREAD

**Issue by tiru1930** [adipandas/multi-object-tracker#11]
Hi 

I am trying pre-trained model with one of the custom video file, for which tracking ids are keep on changing. How can I make sure the tracking ids are consistent over the entire video duration.

**Comment by adipandas** [comment]
@tiru1930, currently I am just using a greedy way of track assignments. And based on heuristic that an object lost in tracking for more that 5 frames is  considered

**Comment by adipandas** [comment]
I have included various trackers in the recent update.
Kalman Filter based trackers such as SORT or CentroidKF_Tracker may be useful for your use-case.
