### ISSUE TITLE
Tracking one object when no object detected

### ISSUE THREAD

**Issue by talha0324** [adipandas/multi-object-tracker#21]
Hey. so I have these bounding boxes, confidence, classes as empty, when I send it to update function. I get 1 object as being tracked. 
I'm using SORT(..) object.

![image](https://user-images.githubusercontent.com/23639404/108761468-b8136d80-7570-11eb-826a-8e0829df9d78.png)

**Comment by adipandas** [comment]
I was not able to reproduce this error. I tried as you are showing here. It is likely, you created this instance of object tracker before and used it for some detection and tracking. Later, you may have used the same tracker instance by passing empty data. It is likely that you are getting the buffer values from previous data.

I ran the following code:

```
def main(tracker):
    for i in range(1000):
        bboxes, confidences, class_ids = np.array([]), np.array([]), np.array([])
        tracks = tracker.update(bboxes, confidences, class_ids)
        print(tracks)

tracker = SORT(max_lost=3, tracker_output_format='mot_challenge', iou_threshold=0.3)
main(tracker)
```

I got the following output:
```
[]
[]
[]
[]
...
```
