### ISSUE TITLE
SORT Tracker reassigns new ID to an already tracked object

### ISSUE THREAD

**Issue by sampreets3** [adipandas/multi-object-tracker#23]
Hello, I am trying to implement the tracker to track custom classes _(tree, wooden post, metal post)_. I am running the mot_yolov3.py file with minor changes. I observe that after a few frames where an object is detected, two things happen:

- the tracker loses track of the object
- when the object reappears, the tracker assigns it a new ID

![pic-problem](https://user-images.githubusercontent.com/25011971/114718707-8cbe2b00-9d36-11eb-835f-83744611289b.png)

If you take a look at the image you will see that the metal post is ID 10 at Frame 43 and ID 11 at Frame 54. In between these two frames, the tracker either lost track (did not display) or tracked it with the correct ID. 

How can this issue be fixed? 
Thanks in advance!

 **EDIT:** I am also facing the Issue pointed out in #22, I will implement the change @cnavarrete has mentioned, and will see if that is a fix

**Comment by adipandas** [comment]
Hi @sampreets3 
I have pushed the updated version of SORT and some minor updates in the latest commits.
I hope it resolves your issue.

Refer **[this](https://github.com/adipandas/multi-object-tracker/tree/68981f363471dfbef39b19e7323d1d3a9a507a5a)** commit for more details.

Thank you.
