### ISSUE TITLE
In the SORT tracker, IOU threshold is not working.

### ISSUE THREAD

**Issue by studian** [adipandas/multi-object-tracker#25]
In the SORT tracker, even if the IOU threshold is changed, the tracking performance does not change.

**Comment by adipandas** [comment]
#22 #23

**Comment by adipandas** [comment]
I have updated the code with bug fixes in SORT. I hope this issue will be resolved as well.
Please let me know if you come across other bugs.

Refer **[this](https://github.com/adipandas/multi-object-tracker/tree/68981f363471dfbef39b19e7323d1d3a9a507a5a)** commit.

Thank you.
