### ISSUE TITLE
what is max_lost?

### ISSUE THREAD

**Issue by studian** [adipandas/multi-object-tracker#26]
In IOUTracker, you have referred to "https://github.com/bochinski/iou-tracker".
'max_lost' in your code is the same concept as 't_min' (minimum track length in frames) in the iou-tracker of Bochenski? Or, is it the opposite concept?

**Comment by adipandas** [comment]
`max_lost` is for Maximum number of consecutive frames object was not detected. I think `t_min` was for the minimum number of detections of the object in the original implementation. It is kinda opposite concept.
