### ISSUE TITLE
Do you have any plan to add V-IOU Tracker?

### ISSUE THREAD

**Issue by studian** [adipandas/multi-object-tracker#27]
Do you have any plan to add V-IOU Tracker ("Extending IOU Based Multi-Object Tracking by Visual Information by E. Bochinski, T. Senst, T. Sikora")?

**Comment by adipandas** [comment]
I had a plan to include it. But I got busy with my work and could not complete that part. I also need to include some tests to make sure everything works OK. As of now, I am not working on it. You are welcome to send any pull request if you happen to implement it. I will be happy to include you as a contributor to this project.

Thank you.
