### ISSUE TITLE
AttributeError: 'SORT' object has no attribute 'track'

### ISSUE THREAD

**Issue by serdarakyol** [adipandas/multi-object-tracker#28]
Hello,
I was following to "How to use?: Examples" step by step and I got this error.

I am using RetinaNet for object detection. I get my detections, scores and labels. I tried to implement sort into my code as following:
```
from motrackers import SORT

tracker = SORT(max_lost=3)
boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))  #  get prediction
output_tracks = tracker.track(boxes[0], scores[0], labels[0])
```
boxes[0] shape is (300,4)
scores[0] and labels[0] shapes are (300,)
but while im running this code. I got this error.
  File "tired2try.py", line 68, in <module>
    output_tracks = tracker.track(boxes[0], scores[0], labels[0])
AttributeError: 'SORT' object has no attribute 'track'

Could someone help me for this error, please?

**Comment by adipandas** [comment]
Hi @serdarakyol ,
I had updated few things in the codes a while ago.
Please refer the updated readme now.

```
output_tracks = tracker.update(...)
```

I also recommend you to refer to the example provided **[here](https://github.com/adipandas/multi-object-tracker/tree/master/examples/example_scripts)**.

I hope this resolves your issue.

Best,
Aditya.
