### ISSUE TITLE
Is there any tracker prediction?

### ISSUE THREAD

**Issue by sodi16** [adipandas/multi-object-tracker#29]
Thanks a lot for your code, I use your tracker with my own model of object detection. Tell me if i am wrong but the tracker you use "udpate" the bbox pixel, class id... but it cannot predict, calculate the bbox emplacement in the next frame, without object detection?
And if it does, wich function do you use to do it. Thanks

**Comment by adipandas** [comment]
Hello @sodi16,
In these implementations I have used Kalman Filtering (KF)  only for ``SORT`` and ``CentroidKF_Tracker``. The KF predictions are encapsulated under the ``update`` method of respective Trackers if they are using Kalman Filter.

You can find usage of the KF `prediction()` methods below:
* ``CentroidKF_Tracker``: [link](https://github.com/adipandas/multi-object-tracker/blob/master/motrackers/centroid_kf_tracker.py#L118)
* ``SORT``: [link](https://github.com/adipandas/multi-object-tracker/blob/master/motrackers/sort_tracker.py#L127)

You will have to access it externally in your codes. May be write additional method in tracker class to return the predictions. Or access the predicted states using something like ``tracker.tracks[track_id].predict()``.

I hope this helps.

Best,
Aditya.

**Comment by sodi16** [comment]
@adipandas 
Thanks a lot for your answer
