### ISSUE TITLE
How to maintain the same ID for a detected object across many frames?

### ISSUE THREAD

**Issue by sinamsl** [adipandas/multi-object-tracker#33]
Hi,

I am trying to use your tracking model, such that when I have detected an object (for example the two pedestrians in the back of the frame) and then they get lost or occluded over the next couple of frames, when they are detected again, they maintain the same ID they had before.  I am using the SORT method. 

![Download (1)](https://user-images.githubusercontent.com/64138234/140620180-be68a2cf-f23d-48aa-81be-193ca9f96873.png)

In the proceeding frames these detected pedestrians get occluded and then they appear again.  The goal is that they have the same ID as they had before dissapearing. 

However I haven't been able to find a solution for this. Is it useful to change the value of _max_lost_ ?

**Comment by adipandas** [comment]
Hi @sinamsl,

The method used for tracking in the current implementation would not ensure assigning the same ID if the lost object is detected after the ``max_lost`` steps. Additionally, using a high value of ``max_lost`` would make the deletion of the tracked objects problematic when they are out of the camera frame.

To ensure the same ``id`` is being assigned once the object is re-detected, I recommend you to look into techniques for **tracking with re-identification**.

I am interested in including a version of object re-identification in this repository. But I haven't been able to make time for this. 
I would suggest you refer to approaches similar to **[this implementation](https://github.com/openvinotoolkit/deep-object-reid)** for more details.

Best regards,
Aditya.
