### ISSUE TITLE
Getting the exact same result when changing tracker type

### ISSUE THREAD

**Issue by ahmadi3d** [adipandas/multi-object-tracker#35]
Hello
I tried changing the tracker type in mot_YOLOv3.py to all the options including ['CentroidTracker', 'CentroidKF_Tracker', 'SORT', 'IOUTracker'] but i keep getting the exact same result, there not even a friction of difference between choosing different trackers, why is that?

**Comment by adipandas** [comment]
@ahmadi3d It is interesting. I did not try such a comparative study (yet). So I may not be able to answer it satisfactorily.
Maybe it is because of various parameter settings in each tracker and/or videos you used.
