### ISSUE TITLE
Starting example is not runnable (uses track method instead of update)

### ISSUE THREAD

**Issue by gboeer** [adipandas/multi-object-tracker#41]
The example code on the very first page is not runnable because it uses function names which are outdated (I guess).

In particular, there is no `track()` function, instead the function should be called `update()`. 

Update:
I just saw that this is only true for the github pages documentation:

https://adipandas.github.io/multi-object-tracker/includeme/readmefile.html?highlight=ioutracker#

**Comment by adipandas** [comment]
@gboeer Fixed the docs. Thanks!
