### ISSUE TITLE
class_ids is not considered in the tracking

### ISSUE THREAD

**Issue by CaterinaFabbri** [adipandas/multi-object-tracker#47]
Hi, I tried the library and it seems that the tracker id can be shared between class_ids. If it's a multi object tracker, is it normal that the track id doesn't reset when it encounters different objects (ie with different class_ids)? Could you please clarify? 

(
class_ids (numpy.ndarray or list): List of class_ids (int) corresponding to labels of the detected object. Default is `None`.

)

**Comment by adipandas** [comment]
Hello @CaterinaFabbri, yes it is not included in the current assignment cost functions.
Formally, if you check the class_ids and add penalty for assignment of one class to another, this could be addressed to some extent during track assignment optimization. I haven't implemented/tested that though. If you consider adding such a feature, you will have to update cost evaluations at below lines:
* See [here](https://github.com/adipandas/multi-object-tracker/blob/f2dd4878514556daa737e3194ee9e4ab49fa997d/motrackers/centroid_kf_tracker.py#LL43C85-L44C1) for track assignment cost in Kalman Filter based trackers
* See [here](https://github.com/adipandas/multi-object-tracker/blob/f2dd4878514556daa737e3194ee9e4ab49fa997d/motrackers/iou_tracker.py#L43) for track assignment cost in SORT.

I hope this helps.
