### ISSUE TITLE
To predict a detection without a detection by a detector

### ISSUE THREAD

**Issue by rose-jinyang** [adipandas/multi-object-tracker#48]
Hello
How are you?
Thanks for contributing to this project.
I am using your method with my custom detector.
My detector sometimes be NOT able to detect an object.
At a certain time, let's suppose that there is NOT a detection of an object by my detector.
Then your method should be able to predict a virtual detection although there is not a detection by the detector.
Of course, I found that the track's info is updated without a corresponding detection.
The Tracker's method "_get_tracks" is finally called in the method "update" of Tracker.

![image](https://github.com/adipandas/multi-object-tracker/assets/47862419/b5da0be5-f3f5-4518-94ff-84b0718a900f)

But this method "_get_tracks" does NOT return any track of which the variable "lost" is greater than 0.

![image](https://github.com/adipandas/multi-object-tracker/assets/47862419/554b3ef5-0920-4ca6-bdf1-2fd7b10a6511)

So a track with at least one lost detection is NOT contained in the finally tracked objects.
I think that this is an issue.

**Comment by adipandas** [comment]
@rose-jinyang Thank you for reporting this. I have fixed this issue in ``v0.0.2``
