### ISSUE TITLE
Bug: SORT always same iou_threshold

### ISSUE THREAD

**Issue by denguir** [adipandas/multi-object-tracker#49]
Hi there, 

I think there is a small bug [here](https://github.com/adipandas/multi-object-tracker/blob/master/motrackers/sort_tracker.py#L143)
iou_threshold is hard coded to 0.3, I think you wanted something more like 

```python
matches, unmatched_detections, unmatched_tracks = assign_tracks2detection_iou(
                bbox_tracks, bbox_detections, iou_threshold=self.iou_threshold)

```

**Comment by adipandas** [comment]
@denguir Thanks for the pull request. I approved it.
