### ISSUE TITLE
Does it use GPU?

### ISSUE THREAD

**Issue by htso** [adipandas/multi-object-tracker#5]
I ran the notebook tracking-yolo-model, and notice my GPU util is 0% throughout. So, question is, how to make it use GPU during inference?

**Comment by adipandas** [comment]
@htso In the current version, I have only used openCV dnn class with the detection inference graphs. This does not support GPU.

Apparently OpenCL support is added but I haven't tested it yet. You can refer [this link](https://answers.opencv.org/question/201456/how-to-run-opencv-dnn-on-nvidia-gpu/) for more details.

To improve upon this, I have a plan to create a tracker package in near future which will be useful while working with deep learning frameworks (tensorflow, pytorch etc.).

If you want to use GPU for inference, you can try it your self by loading the neural networks with your preferred deep learning framework for detection and then using this tracker.

* For tensorflow, [this link](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb) has a good example of how to start with inference.
* For GPU support with lastest version of YOLO, you can refer [this](https://github.com/madhawav/YOLO3-4-Py).

**Comment by htso** [comment]
I saw authors of YOLO v3 (Redmon, Farhadi, 2017) said on a Titan X, the run rate is 22 ms at 28 mAP. Well, on cpu, it's many times slower. Thanks for reply. A GPU version would be very useful.

**Comment by adipandas** [comment]
The updated version of the detection modules can use gpu.
You will have to build the OpenCV from source with cuda flags enabled.
Please refer the read me for more details.
