### ISSUE TITLE
saving object tracking info to file

### ISSUE THREAD

**Issue by htso** [adipandas/multi-object-tracker#6]
I rely on this object tracker repo as an example,

    https://github.com/nwojke/deep_sort

Aft it runs thru a video, it outputs a text file (hypotheses.txt) with the following format.

It has as many rows as the object detected in the video, and for each row, it has these columns

    frame #, object ID, x, y, width, height, other info

This is quite useful for further analysis and assessment with ground truth.

It'd be great if you could do something similar in the notebooks.

**Comment by adipandas** [comment]
Hello @htso, thank you for the suggestions.
I have updated the codes and kept it simple to understand/use. Please refer [this code](https://github.com/adipandas/multi-object-tracker/blob/master/examples/SimpleTracker2-caffe-model-mobilenetSSD.ipynb) for the feature you suggested.
You can log the tracker data in any file (`.csv`, `.txt`, etc.) as per your convenience.

Best regards,
Aditya.
