### ISSUE TITLE
error while loading the model.

### ISSUE THREAD

**Issue by saisarat12345** [adipandas/multi-object-tracker#8]
Hi while running the tensorflow tracker iam unable to load the tensorflow model using open cv as written in the code.the following is the error iam getting when loading a model. C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_graph_simplifier.cpp:960: error: (-215:Assertion failed) nodesMapIt != nodesMap.end() in function 'cv::dnn::dnn4_v20191202::sortByExecutionOrder'..how can i solve this error?.please help me with this

**Comment by adipandas** [comment]
Hello @saisarat12345, I have developed and tested this code on ubuntu. I am not able to reproduce this error. I will suggest you to try reinstalling opencv using pip install.

**Comment by saisarat12345** [comment]
hey @adipandas ..thanks for the reply..i could able to solve the issue. i generated a new  text graph representation from the frozen.pb model as provided in the link below:
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

then i ran the model using newly generated .pbtxt and the original .pb file and it worked for me.
